version: 2.1
setup: false

aliases:
  - &global-context
    context: newfront-global

filters: &always_run
  tags:
    only: /.*/

executors:
  eks-executor:
    docker:
      - image: newfront/app-crafter-eks:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPELINE_NUMBER: << pipeline.number >>


commands:
  docker-login:
    description: Docker setup and login
    steps:
      - run: echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin


jobs:
  build_ping_pong_image:
    executor: eks-executor
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - docker-login
      - run:
          name: Build ping-pong docker image
          command: |
            docker build -t newfront/ping-pong:latest .
      - run:
          name: Tag ping-pong Docker image
          command: |
            docker tag newfront/ping-pong:latest newfront/ping-pong:1
      - run:
          name: Push ping-pong Docker image
          command: |
            docker push newfront/ping-pong:1
            docker push newfront/ping-pong:latest


workflows:
  build_ping_pong_image:
    jobs:
      - build_ping_pong_image:
          <<: *global-context
          filters: *always_run
