version: 2.1
setup: false

aliases:
  - &global-context
    context: newfront-global

filters: &always_run
  tags:
    only: /.*/

executors:
  eks-executor:
    docker:
      - image: newfront/app-crafter-eks:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPELINE_NUMBER: << pipeline.number >>

jobs:
  build_ping_pong_image:
    executor: eks-executor
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker
      - docker-login
      - run:
          name: Build app-crafter-eks docker image
          command: |
            cd src/executors/docker
            docker build -t newfront/ping-pong:latest .
      - run:
          name: Tag app-crafter-eks Docker image
          command: |
            docker tag newfront/ping-pong:latest newfront/app-crafter-eks:${CIRCLE_TAG}
      - run:
          name: Push app-crafter-eks Docker image
          command: |
            docker push newfront/ping-pong:${CIRCLE_TAG}
            docker push newfront/ping-pong:latest


workflows:
  build_ping_pong_image:
    jobs:
      - build_ping_pong_image:
          <<: *global-context
          filters: *always_run
