apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - image: tsongpon/pingpong
          name: pingpong
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 8080
      port: 80
      # nodePort: 30080
      protocol: TCP
  selector:
    app: pingpong